"""Benchmark producer adapters."""

from inferdrome.adapters.fake import FakeAdapter, FakeObservation, FakeRunResult
from inferdrome.adapters.sglang import (
    SGLANG_BACKEND,
    SGLANG_BENCHMARK_MODULE,
    SGLANG_DATASET_NAME,
    SGLANG_DEFAULT_ENDPOINT,
    SGLANG_FIXED_RANDOM_RANGE_RATIO,
    SGLANG_FIXED_SHAREGPT_OUTPUT_LEN,
    SGLANG_FIXED_TAG,
    SGLANG_INVOCATION_SCHEMA_VERSION,
    SGLANG_NATIVE_ARTIFACT_NAME,
    SGLANG_OFFLINE_ENVIRONMENT_POLICY,
    SGLANG_REFERENCE_ADAPTER_ID,
    SGLANG_RELEASE_COMMIT,
    SGLANG_SOURCE_REPOSITORY,
    SGLANG_VERSION,
    SglangInvocation,
    SglangInvocationConfig,
    SglangVersionProbeCapture,
    build_sglang_invocation,
    parse_sglang_version_output,
    preflight_sglang_invocation,
    probe_sglang_version,
    validate_sglang_invocation,
)
from inferdrome.adapters.vllm_bench import (
    EndpointPreflightCapture,
    VllmBenchmarkCapture,
    VllmInvocation,
    VllmInvocationPaths,
    VllmVersionProbeCapture,
    build_vllm_invocation,
    execute_vllm_benchmark,
    preflight_attached_endpoint,
    probe_vllm_version,
)

__all__ = [
    "SGLANG_BACKEND",
    "SGLANG_BENCHMARK_MODULE",
    "SGLANG_DATASET_NAME",
    "SGLANG_DEFAULT_ENDPOINT",
    "SGLANG_FIXED_RANDOM_RANGE_RATIO",
    "SGLANG_FIXED_SHAREGPT_OUTPUT_LEN",
    "SGLANG_FIXED_TAG",
    "SGLANG_INVOCATION_SCHEMA_VERSION",
    "SGLANG_NATIVE_ARTIFACT_NAME",
    "SGLANG_OFFLINE_ENVIRONMENT_POLICY",
    "SGLANG_REFERENCE_ADAPTER_ID",
    "SGLANG_RELEASE_COMMIT",
    "SGLANG_SOURCE_REPOSITORY",
    "SGLANG_VERSION",
    "EndpointPreflightCapture",
    "FakeAdapter",
    "FakeObservation",
    "FakeRunResult",
    "SglangInvocation",
    "SglangInvocationConfig",
    "SglangVersionProbeCapture",
    "VllmBenchmarkCapture",
    "VllmInvocation",
    "VllmInvocationPaths",
    "VllmVersionProbeCapture",
    "build_sglang_invocation",
    "build_vllm_invocation",
    "execute_vllm_benchmark",
    "parse_sglang_version_output",
    "preflight_attached_endpoint",
    "preflight_sglang_invocation",
    "probe_sglang_version",
    "probe_vllm_version",
    "validate_sglang_invocation",
]
