#!/usr/bin/env python3
"""Generate committed public schemas from strict Pydantic contracts."""

import argparse
import json
from pathlib import Path

from inferdrome.schema_registry import SCHEMA_MODELS, public_schema

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIRECTORY = REPOSITORY_ROOT / "schemas" / "public" / "v1"


def render_schemas() -> dict[Path, bytes]:
    return {
        SCHEMA_DIRECTORY / filename: (
            json.dumps(public_schema(filename, model), indent=2, sort_keys=True) + "\n"
        ).encode("utf-8")
        for filename, model in SCHEMA_MODELS.items()
    }


def check_schemas(rendered: dict[Path, bytes]) -> int:
    mismatches = []
    for path, expected in rendered.items():
        if not path.exists() or path.read_bytes() != expected:
            mismatches.append(path.relative_to(REPOSITORY_ROOT).as_posix())
    if mismatches:
        print("public schemas are stale or missing:")
        for mismatch in mismatches:
            print(f"  {mismatch}")
        return 1
    print(f"public schemas are current ({len(rendered)} files)")
    return 0


def write_schemas(rendered: dict[Path, bytes]) -> int:
    SCHEMA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for path, content in rendered.items():
        path.write_bytes(content)
    print(f"generated {len(rendered)} schemas in {SCHEMA_DIRECTORY}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed schema bytes differ from generated bytes",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render_schemas()
    return check_schemas(rendered) if args.check else write_schemas(rendered)


if __name__ == "__main__":
    raise SystemExit(main())
