#!/usr/bin/env python3
"""Generate the Qwen3 launch profile, workload, and source fixtures."""

from __future__ import annotations

import argparse
from pathlib import Path

from inferdrome.qwen3_campaign import qwen3_launch_documents
from inferdrome.qwen3_gpu_capacity_extensions import (
    qwen3_capacity_extension_documents,
)
from inferdrome.qwen3_gpu_tiers import qwen3_gpu_execution_documents

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def render_documents() -> dict[Path, bytes]:
    documents = {
        **qwen3_launch_documents(),
        **qwen3_gpu_execution_documents(),
        **qwen3_capacity_extension_documents(),
    }
    return {
        REPOSITORY_ROOT / relative: content
        for relative, content in documents.items()
    }


def check_documents(rendered: dict[Path, bytes]) -> int:
    mismatches = [
        path.relative_to(REPOSITORY_ROOT).as_posix()
        for path, expected in rendered.items()
        if not path.exists() or path.read_bytes() != expected
    ]
    if mismatches:
        print("Qwen3 launch-profile documents are stale or missing:")
        for mismatch in mismatches:
            print(f"  {mismatch}")
        return 1
    print(f"Qwen3 launch-profile documents are current ({len(rendered)} files)")
    return 0


def write_documents(rendered: dict[Path, bytes]) -> int:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    print(f"generated {len(rendered)} Qwen3 launch-profile documents")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed launch-profile bytes differ from generated bytes",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render_documents()
    return check_documents(rendered) if args.check else write_documents(rendered)


if __name__ == "__main__":
    raise SystemExit(main())
