#!/usr/bin/env python3
"""Generate the frozen operational GPU campaign plan and conformance vectors."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from inferdrome.gpu_campaign import campaign_documents

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


def render_documents() -> dict[Path, bytes]:
    return {
        REPOSITORY_ROOT / relative: (
            json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
        ).encode("utf-8")
        for relative, value in campaign_documents().items()
    }


def check_documents(rendered: dict[Path, bytes]) -> int:
    mismatches = [
        path.relative_to(REPOSITORY_ROOT).as_posix()
        for path, expected in rendered.items()
        if not path.exists() or path.read_bytes() != expected
    ]
    if mismatches:
        print("GPU campaign documents are stale or missing:")
        for mismatch in mismatches:
            print(f"  {mismatch}")
        return 1
    print(f"GPU campaign documents are current ({len(rendered)} files)")
    return 0


def write_documents(rendered: dict[Path, bytes]) -> int:
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    print(f"generated {len(rendered)} GPU campaign documents")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed campaign bytes differ from generated bytes",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render_documents()
    return check_documents(rendered) if args.check else write_documents(rendered)


if __name__ == "__main__":
    raise SystemExit(main())
